version: '3.9'

services:
  hotmart-multiagent:
    build: .
    container_name: hotmart-multiagent-app
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    env_file:
      - .env
    command: streamlit run app.py --server.port=8501 --server.address=0.0.0.0
